### ISSUE TITLE
Easter egg?

### ISSUE THREAD

**Issue by GTP95** [minimaxir/big-list-of-naughty-strings#123]
While looking at the .txt file I found this one:
#	Human injection
#
#	Strings which may cause human to reinterpret worldview

If you're reading this, you've been in a coma for almost 20 years now. We're trying a new technique. We don't know where this message will end up in your dream, but we hope it works. Please wake up, we miss you.

Although I found it humourous I don't think it's testing any actual bug, maybe you should consider to remove it. Or maybe just leave it as an easter egg, I just wanted to point it to you.

**Comment by nabijaczleweli** [comment]
> [I'm ok with *some* 4th wall breaks (e.g. the reinterpret wordview string) but I don't want to fill it up with all the memes.](https://github.com/minimaxir/big-list-of-naughty-strings/pull/120#issuecomment-272997602)

**Comment by ssokolow** [comment]
It also serves as a control. (Something that should present no trouble to any test and, if it does, it's not the naughtiness of the string that's causing the problem.)

**Comment by minimaxir** [comment]
Closing since other comments cover the issue adequately.

**Comment by ChipWolf** [comment]
It is there because it is true. We're trying to communicate with you @GTP95

**Comment by KuteKetX** [comment]
@ChipWolf lol

**Comment by lmcarreiro** [comment]
An interesting discussion about this: https://news.ycombinator.com/item?id=18467263

Could it trigger people into psychotic states?
