### ISSUE TITLE
How to use this list in Selenium

### ISSUE THREAD

**Issue by niutech** [minimaxir/big-list-of-naughty-strings#126]
Please provide a basic usage guide on how to feed this list to Selenium and verify the results. Thank you.

**Comment by Potherca** [comment]
You might want to ask that question on either Stackoverflow or the Selenium forum/mail-list...

**Comment by MattPChoy** [comment]
@niutech also this is highly dependent on the website that you're trying to test?

**Comment by niutech** [comment]
I've found the example usage in this post: https://wonderproxy.com/blog/big-list-of-naughty-strings/
