### ISSUE TITLE
'walks into a bar' link broken

### ISSUE THREAD

**Issue by sbuller** [minimaxir/big-list-of-naughty-strings#148]
The link provided in the README is broken; it seems that the destination site has removed all traces of '.aspx', and is blaming others for having outdated links. :(

**Comment by goosehub** [comment]
Could change the link to this twitter post from same user.

https://twitter.com/sempf/status/514473420277694465

**Comment by minimaxir** [comment]
Merged in https://github.com/minimaxir/big-list-of-naughty-strings/commit/c0b5382124e1552497e1a7aefde7e8fe8f2a79c7

I prefer to use the canonical source for citations.
