### ISSUE TITLE
Date/Time/DateTime strings

### ISSUE THREAD

**Issue by rogerdc** [minimaxir/big-list-of-naughty-strings#153]
There should be a section that contains Date, Time, and DateTime strings. Just as numbers can be encoded in various ways, so can these. 

Is there a tutorial on how to alter blns.txt and then generate the other files? If so, I should be able to file a pull request for them. But just off the top of my head, and keeping it to English (the Scunthorpe Problem section and the comments don't contain other languages), I can think of several additions, some valid and some not: 

January 23, 2016
23 JAN 2016
23 JAN 16
23-JAN-2016
23 January 2016
...
Jan. 23, 2016

00:00:00
00:00:00 AM
12:00:00 AM
12:00:00 PM
23:59:59.997
12:00:00
18:48:42
...
7:48 pm

January 23, 2016 12:00 am
23/1/16 14:54
...
20160123T000000

And for things that shouldn't be accepted

February 29, 2017
26:84:94
14:00 pm

The possibilities are endless, but aren't they always? Between the US order of M/D/Y and the European order of D/M/Y, 24 hour time, standardized timestamps, indicating UTC with a Z, would this be a valuable addition to the list?

**Comment by thiagodp** [comment]
@rogerdc Please see #117

**Comment by rogerdc** [comment]
Moved examples to #117 and closing this one.
