### ISSUE TITLE
This is not more naughty-string

### ISSUE THREAD

**Issue by jsroyal** [minimaxir/big-list-of-naughty-strings#154]
I tried and it tweeted.
Here you can see!
![image](https://user-images.githubusercontent.com/10773353/29747289-d87b5020-8b12-11e7-9fba-0bd713fc8918.png)

**Comment by ssokolow** [comment]
Just because one site accepts a given string doesn't mean everyone will handle it properly. This is a list of gotchas that keep re-appearing in new sites and applications.

**Comment by jsroyal** [comment]
Oh' sorry, But need to update gif because which is not show any more. It would be good to show something where it has been failed to handle.

**Comment by minimaxir** [comment]
No, it's still broken, although it gives a even more unhelpful error message.

<img width="653" alt="screen shot 2017-08-27 at 7 50 26 am" src="https://user-images.githubusercontent.com/2179708/29750874-7aac9bae-8afc-11e7-98dc-25f94869f886.png">

You're cheating by *adding content* with the zero-width space. The purpose of the GIF is to show that Twitter can't handle a tweet with length = 0.

**Comment by jsroyal** [comment]
Ok for closing.
![image](https://user-images.githubusercontent.com/10773353/29751841-ae194680-8b70-11e7-96cf-f1f0860ad956.png)
But it has been also handling.Mine, Tweet button disables when 0 width space.
But I think it was a nice hack.
