### ISSUE TITLE
Possibility of adopting a funding model

### ISSUE THREAD

**Issue by SimonCropp** [minimaxir/big-list-of-naughty-strings#186]
@minimaxir 

  I wanted to raise the possibility of moving to a more maintainable model for your project going forward. Too many open source projects survive through the significant contributions of a very small core team, usually in their free time. For various reasons, the community using a project are not active enough to keep the project alive without those core contributors. This causes problems with [bus factor](https://en.wikipedia.org/wiki/Bus_factor), [systemic problems with diversity](https://www.ashedryden.com/blog/the-ethics-of-unpaid-labor-and-the-oss-community#diversity), quality projects not getting properly supported and sometimes abandoned.

I recently changed Fody to a "strongly encouraged u pay a token monthly fee" model https://github.com/Fody/fody#licensingpatron-faq

I am in no way suggesting you take the exact approach. There is a whole spectrum of options based on things like level/method of enforcement, dual licensing, sponsorship, pay for commercial. or the simplest having a statement "if u cant support the project with time, help us with a small donation".

There are a few options that can help u minimize the overhead of taking the above approach. for example

- https://licensezero.com/
- https://opencollective.com/
- https://www.patreon.com/
- https://tidelift.com/

Some further reading

- https://techcrunch.com/2018/06/23/open-source-sustainability/
- https://jaxenter.com/who-funds-open-source-projects-133222.html

Let me know if you want to get on a call to discuss further. Or feel free to ignore with "nah we r fine", i wont be offended :)

**Comment by ssokolow** [comment]
To be honest, this comes across spammy and, if you post messages like these, you're at risk of having some random subscriber to the issue tracker in question report your account for spamming.

**Comment by SimonCropp** [comment]
@ssokolow thanks for the feedback. i will take that on board.

do u have any feedback on my actual proposal?

**Comment by ssokolow** [comment]
You'll have to wait for @minimaxir for definitive answers, but the BLNS isn't really the type of project where maintainership is a huge concern.

A corpus of test strings with some helper scripts to regenerate the alternative formats requires far less active maintainership than a typical program would, and it takes minimal expertise for someone else to step up and start maintaining a fork should @minimaxlr become unavailable.

**Comment by minimaxir** [comment]
I have a Patreon that I use for my other, more complicated projects. However, I will not link it to this project, nor implement any other monetization for it, because **it's a .txt file**, with the majority of contributions coming from others.

I should be more responsive to issues/PRs on this repo, and I apologize for that, but forcing monetization won't impact that fact.

**Comment by SimonCropp** [comment]
@minimaxir thanks for the consideration
