### ISSUE TITLE
What's so naughty about 'evaluate' and 'mocha'?

### ISSUE THREAD

**Issue by nderjung** [minimaxir/big-list-of-naughty-strings#188]
☝️

**Comment by scribblemaniac** [comment]
From [the wikipedia link right above these words](https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt#L667):

> In 2001, Yahoo! Mail erroneously changed words, including medireview in place of medieval. That year Yahoo! introduced an email filter which automatically replaced JavaScript-related strings with alternative versions, to prevent the possibility of JavaScript viruses in HTML email. The filter would hyphenate the terms "Javascript", "Jscript", "Vbscript" and "Livescript", and replaced "eval", "mocha" and "expression" with the similar but not quite synonymous terms "review", "espresso" and "statement", respectively. Assumptions were involved in the writing of the filters: no attempts were made to limit these string replacements to script sections and attributes, or to respect word boundaries, in case this would leave some loopholes open.

**Comment by nderjung** [comment]
Oh my bad, cheers! 👍
