### ISSUE TITLE
add null byte

### ISSUE THREAD

**Issue by jimmywarting** [minimaxir/big-list-of-naughty-strings#194]
say that you have two files on the disc
- secret.json
- profile.jpg

the server allows you to read the content of any file ending with with jpg, so it is automatically suffixed with `+".jpg"`

```js
readFile(path + ".jpg")
```

but if you could trick it maybe you can get away with reading secret.json if you say that you want to read `secret.json\0whatever_not_included`

**Comment by GrosSacASac** [comment]
In what environment does that happen ?
