### ISSUE TITLE
single blank

### ISSUE THREAD

**Issue by ecki** [minimaxir/big-list-of-naughty-strings#25]
... single blank or trailing/leading blanks are missing, especilly " ". Also "%" and "_" (SQL escapes)

**Comment by stuartpb** [comment]
Trailing blanks compromise manual usability of the file (they conflict with sensible text editor defaults). [See the "Contributions" section of the README.](https://github.com/minimaxir/big-list-of-naughty-strings#contributions)

**Comment by ecki** [comment]
No problem for the JSon file. You can even hex encode them.

**Comment by minimaxir** [comment]
Added in https://github.com/minimaxir/big-list-of-naughty-strings/commit/4fdd7318621f53e23030dd738687836ab91457f1
