### ISSUE TITLE
Is this repo still "alive"?

### ISSUE THREAD

**Issue by norcino** [minimaxir/big-list-of-naughty-strings#252]
Hi @minimaxir is this repos still alive?
I see many pull requests and suggestions but it has been more than 2 years that this was not updated.

Thanks

**Comment by shalak** [comment]
Yeah, looks dead. Anybody seen more recent and maintained forks of this?

**Comment by helloromero** [comment]
@shalak nope see here -> https://github.com/minimaxir/big-list-of-naughty-strings/forks?include=active&page=1&period=2y&sort_by=last_updated

**Comment by el-nuru** [comment]
wonder if there is any recommended fork, I see a ton of them but I'm not sure where the community migrated to

**Comment by ross-spencer** [comment]
If you sort the list, the one with the most stars has two stars so I suspect there hasn't been a "migration event" yet, but it'd be great to hear from @minimaxir about what they think, whether they'd like to add contributors here or other options to see it up to date?

**Comment by minimaxir** [comment]
This list is literally a text file, with no dependencies and very new advances in the field of adversarial strings. By construction, it's not going to be as active as other projects on GitHub.

I do not appreciate the accusations of neglect, there just hasn't been much activity and PRs that don't add much unique value.

**Comment by m0rtalis** [comment]
@minimaxir Be realistic, the only issue you commented on in the last year was this one accusing you of neglect. I have not seen any other activity here.
There are relevant and important PRs open that get simply ignored.

**Comment by geeknik** [comment]
> @minimaxir Be realistic, the only issue you commented on in the last year was this one accusing you of neglect. I have not seen any other activity here. There are relevant and important PRs open that get simply ignored.

That's the great thing about GitHub and open source. You can fork this repository and then add everything to it. :)

**Comment by shalak** [comment]
> > @minimaxir Be realistic, the only issue you commented on in the last year was this one accusing you of neglect. I have not seen any other activity here. There are relevant and important PRs open that get simply ignored.
> 
> That's the great thing about GitHub and open source. You can fork this repository and then add everything to it. :)

This is also causes the worst thing about open source - fragmentation and dilution of community efforts.

**Comment by prochac** [comment]
@minimaxir To communicate the project is dead/done, you may archive it here on GitHub, then you will "free" yourself.
