### ISSUE TITLE
SMPPoker Situs Agen Judi Poker Online Uang Asli Terpercaya Indonesia

### ISSUE THREAD

**Issue by prasta21** [minimaxir/big-list-of-naughty-strings#38]
There was an old woman lived near the <a href="http://crazy-venus.blogspot.com/2015/08/smppoker-situs-agen-judi-poker-online-uang-asli-terpercaya-indonesia.html"target="_blank"title="SMPPoker Situs Agen Judi Poker Online Uang Asli Terpercaya Indonesia">Kapuas River</a>, West Kalimantan. She had two sons. Her husband had died a long time ago. The woman took care of her sons by herself. She taught them to be independent. The two sons were teenagers. They wanted to have a better life. Every day they saw big ships sailing along the Kapuas River. They saw rich merchants with beautiful ships. They also wanted to become rich merchants. They really wanted to have big and beautiful ships. The two sons told their plans to their mother. The woman was very sad. She did not want to lose her children. However, they insisted that they would come back soon. And they also promised to be back home with a lot of money. The woman could not hold them any longer. She finally let them go. And before the sons left, they gave their mother their chicks. They said that they would come home when the chicks grew as cocks.
The two brothers joined a big ship. The owner of the ship was a rich merchant. He gave them a job in his ship. They were very happy. Their dream started to come true. After working for the rich merchant for some time, the two brothers bought their own ships. Each of them bought a small ship. They worked very hard and slowly they became very rich. The two brothers were famous. Many people were amazed with their wealth and their beautiful and big ships. Many young girls fell in love with them. And finally the two brothers got married. Their wives were really beautiful. It had been a really long time since the two brothers left their home. They wanted to visit their hometown. The two brothers told their wives and their crew that they would sail to <a href="http://crazy-venus.blogspot.com/2015/08/smppoker-situs-agen-judi-poker-online-uang-asli-terpercaya-indonesia.html"target="_blank"title="SMPPoker Situs Agen Judi Poker Online Uang Asli Terpercaya Indonesia">Kapuas River</a>, their hometown. The ships sailed side by side. And every time the ships passed by at a harbor, people were always talking about them. They were talking about the rich brothers who would go back home. The news about the two brothers was spreading very fast. Their mother also heard the news and she was extremely happy. The woman had been waiting for their children. She was old and very weak. Every day she was always thinking about her sons. And when her sons' ships finally arrived, she brought the cocks. She wanted to show the cocks to her children. First she came to the oldest son.
"My Son <a href="http://crazy-venus.blogspot.com/2015/08/smppoker-situs-agen-judi-poker-online-uang-asli-terpercaya-indonesia.html"target="_blank"title="SMPPoker Situs Agen Judi Poker Online Uang Asli Terpercaya Indonesia">SMPPoker Situs Agen Judi Poker Online Uang Asli Terpercaya Indonesia</a>, it's me. I am your mother. Look! I brought your cock." The oldest son was shocked to see his mother. She was old and looked shabby. The oldest son was ashamed to see his own mother.
"No! I don't know you! You are not my <a href="http://crazy-venus.blogspot.com/2015/08/smppoker-situs-agen-judi-poker-online-uang-asli-terpercaya-indonesia.html"target="_blank"title="SMPPoker Situs Agen Judi Poker Online Uang Asli Terpercaya Indonesia">SMPPoker Situs Agen Judi Poker Online Uang Asli Terpercaya Indonesia</a> mother. Go away!"
The old woman was very sad. She was crying. Then she went to the second ship. It belonged to his second son. Sadly, his second son also behaved badly. He also denied the woman as his mother. The woman was very sad. She never thought it would happen to her. Her sons ignored her and did not want to admit her as their mother. She prayed to God. She asked God to punish her children. God heard the prayer. Suddenly a heavy storm attacked the river. The rain fell down heavily. The two brothers wanted to save their lives. Their ships sailed very fast. But they could not save their lives. The storm made their ships sink. And after the storm was over, people saw two islands in the middle of  Kapuas River. The islands looked like two ships sailing in the, race competition. People then named the islands as Belumbak Island. Belumbak is from the word 'berlomba' or '<a href="http://crazy-venus.blogspot.com/2015/08/smppoker-situs-agen-judi-poker-online-uang-asli-terpercaya-indonesia.html"target="_blank"title="SMPPoker Situs Agen Judi Poker Online Uang Asli Terpercaya Indonesia">SMPPoker Situs Agen Judi Poker Online Uang Asli Terpercaya Indonesia</a>'.

**Comment by minimaxir** [comment]
no
