### ISSUE TITLE
Escape Character '\', or '\\' for certain uses.

### ISSUE THREAD

**Issue by DripDrop14** [minimaxir/big-list-of-naughty-strings#40]
For the 'Reserved Strings' category, can be used in string interpretation to wreak havoc, such as invalid escape character usage. Overall dangerous.

**Comment by minimaxir** [comment]
Merge accepted in https://github.com/minimaxir/big-list-of-naughty-strings/commit/bdbcb6c4f12950ce2caa50865c8ae2a48572fcb4
