### ISSUE TITLE
Implement multi-language string-sanitization framework utilizing JSON file?

### ISSUE THREAD

**Issue by DripDrop14** [minimaxir/big-list-of-naughty-strings#44]
I am suggesting the creation of a library (JavaScript, Python, Java, C/C++, etc.) for sanitizing strings using the JSON file blns.json.

**Comment by ssokolow** [comment]
It's not that simple. Often, problems arise after the sanitization/validation stage based on how the components of the systems interact and, if you just strip characters like that, you wind up with Fanfiction.net converting `100%` to `100` in posted chapters or various sites converting `O'Henry` to `OHenry`.

**Comment by DripDrop14** [comment]
Good point... I may fork the repo and try some tests regarding this (In javascript), but I had an idea of a more or less customizable library, that can selectively filter out the categories stored in the BLNS files (e.g. Reserved Words, Numeric, etc.) so it can be customized for each use.
