### ISSUE TITLE
Comma as numeric decimal point denotion

### ISSUE THREAD

**Issue by Towerful** [minimaxir/big-list-of-naughty-strings#48]
Many languages use the comma `,` to denote decimals, and the period `.` to denote thousands separation.  https://en.wikipedia.org/wiki/Decimal_mark  
Is it worth, in the numeric section, having a variety of these:

    1,000.00
    1000.00
    1.000,00
    1000,00

whilst perhaps not naughty strings, a coder that is used to comma-denoted-decimal may be caught out.

**Comment by Rychard** [comment]
:+1:

**Comment by minimaxir** [comment]
Yep, sounds good to me. LOC testing is always good. :)

**Comment by libwtf** [comment]
don't forget switzerland ;) :
<code>1'000.00</code>
<code>1'000'000.00</code>

and additional to those at the top :
<code>1.000.000,00</code>
<code>1,000,000.00</code>

**Comment by Haroenv** [comment]
There's also

`1 000 000,00`

and 

`1 000 000.0`
