### ISSUE TITLE
Section for Date/Time values

### ISSUE THREAD

**Issue by minimaxir** [minimaxir/big-list-of-naughty-strings#55]
Would a section for Date/Time values be a productive idea? To my knowledge, systems don't parse raw DateTime strings unless you explicitly say if it's a DateTime parser, and DateTime parsers don't take in raw DateTime strings, opting instead to use some sort of Date/Time selector widget on the client and doing the calculation on server.

**Comment by StephanErb** [comment]
Invalid dates like 2015-02-30 are also common source for hickups.

**Comment by andrew-hoffman** [comment]
February 29th, 1900 is still a valid date in Excel but does not really exist.

**Comment by breadtk** [comment]
:+1: 

Additional dates to consider: [end of unix time](https://en.wikipedia.org/wiki/Unix_time#Representing_the_number), very distant future (e.g. 42424242-01-01), [leap seconds](https://en.wikipedia.org/wiki/Leap_second), and basically everything else in the [Time formatting and storage bugs](https://en.wikipedia.org/wiki/Time_formatting_and_storage_bugs) wikipedia entry.

**Comment by minimaxir** [comment]
Closing since accidentally made a dupe (https://github.com/minimaxir/big-list-of-naughty-strings/issues/117) which is cooler.
