### ISSUE TITLE
Smart quotes in HTML

### ISSUE THREAD

**Issue by schmod** [minimaxir/big-list-of-naughty-strings#62]
A Not-So-Hypothetical situation:

* Your customer walks into a bar.  
* Your customer orders up some XML.  Yum!
* The customer isn't satisfied, so they edit the XML by hand.  In Microsoft Word.
* Suddenly, your customer's XML is filled with smart quotes.  

What's a poor parser to do?

```xml
<foo val=“bar” />
```

---

I'm not sure how much of a problem that this actually is, so feel free to close this if it's a little too far-fetched.

It's one of those things that's technically-not-exactly-wrong, but also almost-definitely-not-right.

**Comment by ecnepsnai** [comment]
Well it's not really a big problem, but this isn't the big list of problematic strings, just a list of naughty strings, and those stupid smart quotes are very naughty **THANK YOU VERY MUCH WORDPRESS**.

**Comment by bbarry** [comment]
<foo val=“bar” /> 
    <foo val=”bar“ /> 
    <foo val=`bar' />

**Comment by MrMormon** [comment]
foo val=`bar' looks like a LaTeX one.

**Comment by jfinkhaeuser** [comment]
GNU command line arguments documentation, rather.
