### ISSUE TITLE
`<plaintext>`

### ISSUE THREAD

**Issue by kizu** [minimaxir/big-list-of-naughty-strings#63]
`<plaintext>` tag is really naughty, as it is imposible to close it in any way using just HTML. [Example at codepen](http://codepen.io/kizu/pen/zGVmKb?editors=100).

Actually, in most cases even just `<plaintext` string in HTML context would be enough to break stuff.

**Comment by DripDrop14** [comment]
Oh my... This could be catastrophic... I support this issue.

**Comment by minimaxir** [comment]
Added in #64
