### ISSUE TITLE
suggest more variants of Inf/NaN

### ISSUE THREAD

**Issue by jhi** [minimaxir/big-list-of-naughty-strings#67]
I suggest adding the following:

# Whether "Infinity" is the stringification, and whether Infinity is the the numification,
# depends on the C library.
INF

# Win32 (Visual C, really) variants of the infinity and nan
# (see http://blogs.msdn.com/b/oldnewthing/archive/2013/02/21/10395734.aspx)
# Yes, the # really is part of the stringification.
# The 1#IND is a type of quiet nan.
1#INF
-1#IND
1#QNAN
1#SNAN
1#IND

**Comment by minimaxir** [comment]
Added in https://github.com/minimaxir/big-list-of-naughty-strings/commit/99cb86c7f877104b8dec6387c7fe16a3f8b93eea
