### ISSUE TITLE
Not actually NPM module

### ISSUE THREAD

**Issue by DaAwesomeP** [minimaxir/big-list-of-naughty-strings#70]
@minimaxir I saw that there is a `package.json`, but there isn't actually a NPM package attached to it. Would you mind publishing it to NPM?

**Comment by minimaxir** [comment]
I'm note a Node developer (at the moment) so I'm not sure how that process works. I'll look into it.

**Comment by eins78** [comment]
I came here to say the same thing.

@minimaxir It's quite easy:

```
npm login # you'll likely need to create an account
cd $repo
npm publish # on subsequent publishes, the version number needs to be bumped or it will fail
```

**Comment by minimaxir** [comment]
Looks like I have everything working: https://www.npmjs.com/package/big-list-of-naughty-strings

I'll try to keep it updated.
