### ISSUE TITLE
New found string that will crash currently released versions of Chrome Browser

### ISSUE THREAD

**Issue by Marc-Hayes** [minimaxir/big-list-of-naughty-strings#75]
The following string without the space has been found to crash currently released Chrome Browsers
http: //a/%%30%30

**Comment by minimaxir** [comment]
Yup, [found the bug](https://code.google.com/p/chromium/issues/detail?can=2&q=533361&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&id=533361) in Chromium. (sounds like a pesky null character.)

Will definitely add.

**Comment by minimaxir** [comment]
What happens is:

%30 is decoded to "0"
%30 is decoded to "0"
The new "%00" is decoded to the lovely null character. Boom.

String added in https://github.com/minimaxir/big-list-of-naughty-strings/commit/7a9b797500364dc771067dd21988ffddca21159f
