### ISSUE TITLE
Go package

### ISSUE THREAD

**Issue by willfaught** [minimaxir/big-list-of-naughty-strings#79]
Is the owner open to adding a .go file to make this repo importable as a Golang package? I can do a PR if so.

**Comment by minimaxir** [comment]
Sure, just send a PR. (as I know nothing about Golang packages)

**Comment by minimaxir** [comment]
Added in https://github.com/minimaxir/big-list-of-naughty-strings/commit/066caafe87f9c1d92318f272bce6ea8643088b24
