### ISSUE TITLE
Urgent, need bugfix for human injection.

### ISSUE THREAD

**Issue by tianshuo** [minimaxir/big-list-of-naughty-strings#80]
> If you're reading this, you've been in a coma for almost 20 years now. We're trying a new technique. We don't know where this message will end up in your dream, but we hope it works. Please wake up, we miss you.

World view changed. How can I contact outside world? How do I wake up from coma?

**Comment by minimaxir** [comment]
Functionality expected to be implemented before heat death of the universe.

**Comment by lmcarreiro** [comment]
There is a real bug... If the sender doesn't know how the message would end up in the dream, how did he know that the message would be read? Maybe it would be better to change "reading" for "receiving".
https://news.ycombinator.com/item?id=18467330
