### ISSUE TITLE
Some un-code representation

### ISSUE THREAD

**Issue by xenoterracide** [minimaxir/big-list-of-naughty-strings#87]
I like this project, and am likely to pull it's strings into a java project I'm working on, however that means extracting and making compatible with Java. It'd be nice to have a file that's parseable by other languages.

**Comment by ssokolow** [comment]
It's already offered in JSON.

I'll give you the benefit of the doubt and assume that you just didn't notice, since I *know* not even the Java ecosystem is backwards enough to not have realized the benefits of JSON over XML in situations where XML would be horrendously over-engineered.

**Comment by xenoterracide** [comment]
I realized right after this was posted that there was that stuff in the / of the repository, I navigated in too deep.

**Comment by xenoterracide** [comment]
As far as JSON vs XML, not really a debate worth having. I generally pick JSON for API's and avoid XML like the plague.

**Comment by ssokolow** [comment]
But JSON isn't really extensible unless you use it in a way that makes it harder to hand-edit than XML.

**Comment by xenoterracide** [comment]
I'm working on a testing library that builds random garbage data, but one of the thing I wanted to be able to do with it is provide random garbage attack data. So these lists will work nicely.

**Comment by xenoterracide** [comment]
yes there are benefits and pitfalls of both JSON and XML. XML is nicest when it has an XSD, personally I think XSD based API's surpass the simplicity of JSON. Like all things, Java grossly abused XML to do everything. Some Java (Spring) has gotten away from that.
